nome:
  ambiente: ambiente default
serie-prop:
  prop11: valore String
  prop12:
    prop121: 121
  prop2: 1.2
  data: 23/12/1980

logging:
  level:
    root: INFO    # Livello di log generale
    and.learn: DEBUG   # Livello di log personalizzato per il mio package
  file:
    name: ${user.home}/log/SpringBootServer.log   # Percorso del file di log
    max-size: 5MB       # Dimensione massima prima della rotazione
    max-history: 5       # Numero massimo di file storici
  pattern:
    file:    "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{50}.%M - Line:%L - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{50}.%M - Line:%L - %msg%n"

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers #  Altrimenti per abilitare tutti gli endpoint Actuator metti "*"
  endpoint:
    health:
      show-details: ALWAYS  # Mostra dettagli nei controlli di stato. Per dettagli si intende gli indicatori di default e quelli personalizzati
    loggers:
      enabled: true
  health:
    defaults:
      enabled: false  # Disabilita tutti gli indicatori di default che offre Spring, se metti true compare qualche info in più

#Cache con ehcache
spring:
  cache:
    type: jcache
    jcache:
      config: classpath:cache/ehcache.xml # Specifica dove si trova il file di conf da leggere

